// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWOypC8JAqCtvf-sDlCfCnyZzH4J36ABQ',
    appId: '1:157269568434:web:04c297e5a8b285388612ab',
    messagingSenderId: '157269568434',
    projectId: 'swiftbill-ed9cb',
    authDomain: 'swiftbill-ed9cb.firebaseapp.com',
    storageBucket: 'swiftbill-ed9cb.firebasestorage.app',
    measurementId: 'G-S072WPZGWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvKpCm8RPjGhqzjV0gagXjMJP7EP425-g',
    appId: '1:157269568434:android:507b375c8bbbf2ce8612ab',
    messagingSenderId: '157269568434',
    projectId: 'swiftbill-ed9cb',
    storageBucket: 'swiftbill-ed9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFGhhjyfbXlIbp1CYyR1o71YALQ9mVfGM',
    appId: '1:157269568434:ios:62662f4dda61907d8612ab',
    messagingSenderId: '157269568434',
    projectId: 'swiftbill-ed9cb',
    storageBucket: 'swiftbill-ed9cb.firebasestorage.app',
    iosBundleId: 'com.example.swiftbillApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFGhhjyfbXlIbp1CYyR1o71YALQ9mVfGM',
    appId: '1:157269568434:ios:62662f4dda61907d8612ab',
    messagingSenderId: '157269568434',
    projectId: 'swiftbill-ed9cb',
    storageBucket: 'swiftbill-ed9cb.firebasestorage.app',
    iosBundleId: 'com.example.swiftbillApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWOypC8JAqCtvf-sDlCfCnyZzH4J36ABQ',
    appId: '1:157269568434:web:fcaef3945888a35e8612ab',
    messagingSenderId: '157269568434',
    projectId: 'swiftbill-ed9cb',
    authDomain: 'swiftbill-ed9cb.firebaseapp.com',
    storageBucket: 'swiftbill-ed9cb.firebasestorage.app',
    measurementId: 'G-1RCHQE4BPV',
  );
}
